import os
import json
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

# --- Configuration ---
METADATA_FILE = 'image_metadata.json'
FAISS_INDEX_FILE = 'text_faiss.index'

# We use a lightning-fast text-to-text model now, since LLaVA already did the vision part
print("[*] Loading semantic text model...")
model = SentenceTransformer('all-MiniLM-L6-v2')

def build_search_index(metadata_db):
    print("[*] Building high-speed vector database from metadata...")
    
    image_paths = list(metadata_db.keys())
    descriptions = list(metadata_db.values())
    
    # Convert all the rich text descriptions into math vectors
    embeddings = model.encode(descriptions, show_progress_bar=True)
    embeddings = np.array(embeddings).astype('float32')
    faiss.normalize_L2(embeddings)
    
    # Build FAISS index
    dimension = embeddings.shape[1]
    index = faiss.IndexFlatIP(dimension)
    index.add(embeddings)
    
    # Save it to disk so we don't have to rebuild it every time
    faiss.write_index(index, FAISS_INDEX_FILE)
    
    return index, image_paths

def main():
    if not os.path.exists(METADATA_FILE):
        print(f"[!] '{METADATA_FILE}' not found. Please run smart_indexer.py first!")
        return
        
    # Load the descriptions generated by LLaVA and FaceNet
    with open(METADATA_FILE, 'r') as f:
        metadata_db = json.load(f)
        
    if not metadata_db:
        print("[!] Metadata file is empty. Run smart_indexer.py on some photos.")
        return

    # Load or build the FAISS index
    if os.path.exists(FAISS_INDEX_FILE):
        print("[*] Loading existing search index...")
        index = faiss.read_index(FAISS_INDEX_FILE)
        image_paths = list(metadata_db.keys())
    else:
        index, image_paths = build_search_index(metadata_db)

    print("\n=== Multi-Model Photo Search Active ===")
    print("Search by person, environment, or both (e.g., 'Rudra sitting at a desk')")
    
    while True:
        query = input("\nSearch query (or 'exit'): ")
        if query.lower() == 'exit':
            break
            
        # Convert your search text into a vector and find the closest metadata match
        query_vector = model.encode([query]).astype('float32')
        faiss.normalize_L2(query_vector)
        
        distances, indices = index.search(query_vector, k=3)
        
        print("\n[ Top Matches ]")
        for i in range(len(indices[0])):
            match_idx = indices[0][i]
            if match_idx != -1:
                path = image_paths[match_idx]
                score = distances[0][i]
                context = metadata_db[path]
                print(f"File: {path}")
                print(f"Match Score: {score:.4f}")
                print(f"Context: {context}\n")

if __name__ == '__main__':
    main()
